## ----setup, include=FALSE------------------------------------------------
knitr::opts_chunk$set(echo = TRUE)


## ----Libraries, message=FALSE, warning=FALSE, EVAL=FALSE, include=FALSE----

# This is where we import our libraries and files. We'll also add some information to be included on our plots

library(knitr)
library(tidyverse)
library(RColorBrewer)
library(lubridate)

Cal_Fires <- read_csv("week21_calfire_frap.csv") %>%
  mutate(Alarm_Date = ymd(alarm_date)) %>%
  mutate(Contained_Date = ymd(cont_date)) %>%
  mutate(Year = year(Alarm_Date)) %>%
  rename(Fire_Name = fire_name) %>%
  mutate(cause2 = case_when(cause == 1 | cause == 17 ~ "Natural",
                            cause == 14 | is.na(cause) ~ "Unknown",
                            cause != 1 | cause != 14 | cause != 17 ~ "Human"))

Time_of_Analysis <- now(tz = "America/New_York")
Analyst <- "@jasonmstevens"

plot <-        theme(plot.background = element_rect(fill = "white"))+
               theme(panel.background = element_rect(fill = "white",
                                                     colour="grey50"))+
               theme(plot.title = element_text(face = "bold", 
                                  size = 18,
                                  color = "navy"))+
               theme(axis.title = element_text(face = "bold", size = 16))+
               theme(aspect.ratio = 3.5/5)



## ----Barplot of California Wildfires, echo=FALSE, message=FALSE, warning=FALSE, tidy=TRUE----

Cal_Fires_Bar <- Cal_Fires %>%
  group_by(Year) %>%
  summarize(Burned_Acres = sum(gis_acres), na.rm = TRUE) %>%
  ggplot(aes(Year, Burned_Acres))+
  geom_smooth()+
  geom_bar(stat = "identity")+
  ggtitle("Acres Burned for California Wildfires")+
  labs(x = "Year", y = "Acres Burned",
       subtitle = paste("Generated by", Analyst, "on", Time_of_Analysis))+
  plot

Cal_Fires_Bar



## ----California Wildfires by Month, echo=FALSE, message=FALSE, warning=FALSE, tidy=TRUE----

Cal_Fires_Month <- Cal_Fires %>%
  mutate(Month = month(Alarm_Date, label = TRUE)) %>%
  group_by(Month) %>%
  summarize(Burned_Acres = sum(gis_acres), na.rm = TRUE) %>%
  ggplot(aes(Month, Burned_Acres))+
  geom_smooth()+
  geom_bar(stat = "identity")+
  ggtitle("Acres Burned for California Wildfires\nby Month Since 1950")+
  labs(x = "Month", y = "Acres Burned",
       subtitle = paste("Generated by", Analyst, "on", Time_of_Analysis))+
  plot

Cal_Fires_Month
  



## ----Active Season California Wildfires, echo=FALSE, message=FALSE, warning=FALSE, tidy=TRUE----

Active_Season <- c("Aug", "Sep", "Oct")

Cal_Fires_Active <- Cal_Fires %>%
  mutate(Month = month(Alarm_Date, label = TRUE)) %>%
  filter(Month %in% Active_Season) %>%
  group_by(Year) %>%
  summarize(Burned_Acres = sum(gis_acres), na.rm = TRUE) %>%
  ggplot(aes(Year, Burned_Acres))+
  geom_smooth()+
  geom_bar(stat = "identity")+
  ggtitle("Acres Burned for California Wildfires\n During Active Season by Year")+
  labs(x = "Year", y = "Acres Burned",
       subtitle = paste("Generated by", Analyst, "on", Time_of_Analysis))+
  plot

Cal_Fires_Active
  


## ----Quiet Season California Wildfires, echo=FALSE, message=FALSE, warning=FALSE, tidy=TRUE----

Active_Season <- c("Aug", "Sep", "Oct")

Cal_Fires_Quiet <- Cal_Fires %>%
  mutate(Month = month(Alarm_Date, label = TRUE)) %>%
  filter(!(Month %in% Active_Season)) %>%
  group_by(Year) %>%
  summarize(Burned_Acres = sum(gis_acres), na.rm = TRUE) %>%
  ggplot(aes(Year, Burned_Acres))+
  geom_smooth()+
  geom_bar(stat = "identity")+
  ggtitle("Acres Burned for California Wildfires\n During Quiet Season by Year")+
  labs(x = "Year", y = "Acres Burned",
       subtitle = paste("Generated by", Analyst, "on", Time_of_Analysis))+
  plot

Cal_Fires_Quiet

ggsave(Cal_Fires_Quiet, filename = "Cal_Fire_Quiet.png")
  

